apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  selector:
    matchLabels:
      app: datanode
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - image: gcr.io/temporal-genius-326917/bde2020/hadoop-datanode:1
          imagePullPolicy: Always
          name: datanode
          env:
          - name: SERVICE_PRECONDITION
            value: namenode-service:9000
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://namenode-service:9000
