apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: namenode
  name: namenode-service
  namespace: default
spec:
  ports:
  - name: 9870-to-9870-tcp
    port: 9870
    protocol: TCP
    targetPort: 9870
  - name: 9000-to-9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: namenode
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 34.70.112.6

